#!/usr/bin/env bash
set -e
echo "Building Lip Shade Lab project files..."

mkdir -p '.github/workflows'
cat > '.github/workflows/deploy.yml' << 'ENDOFFILE__github_workflows_deploy_yml'
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build manifest + site
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          NODE_ENV: production
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
ENDOFFILE__github_workflows_deploy_yml

cat > '.gitignore' << 'ENDOFFILE__gitignore'
node_modules
dist
.DS_Store
*.local

# Generated product images/manifest are build output — regenerated by
# `npm run manifest` / the GitHub Action. Keep the source photos in
# /products (tracked), not the derived copies here.
public/products/*
!public/products/.gitkeep
ENDOFFILE__gitignore

cat > 'README.md' << 'ENDOFFILE_README_md'
# Lip Shade Lab

Try lip color shades on your own photo, blended with real color science —
not a flat overlay. Runs entirely in the browser: no server, no database,
your photo never leaves your device.

**[Live demo →](#)** _(update this link once deployed — see below)_

## How it works

1. **Product library.** You drop photos of lip products applied on lips into
   `/products`. The filename becomes the product name. A build script scans
   each photo, samples its color in LAB space, and writes a small JSON
   catalog (`public/products/manifest.json`) — no database needed.
2. **Face + lip detection.** When you upload your own photo, Google's
   MediaPipe Face Landmarker (running fully in-browser via WebAssembly)
   finds ~40 lip-contour points and builds a soft-edged mask of your lips,
   excluding your teeth/mouth interior.
3. **Color-science blending.** Instead of pasting the product's color over
   your lips, the app:
   - Converts both your natural lip color and the product's color into
     **CIE LAB space** (perceptually uniform — separates lightness from
     hue/chroma, unlike RGB).
   - **Keeps your natural lightness/shading** (highlights, shadows, the
     texture and curve of your lips) and swaps in the product's hue and
     chroma — so it looks like product on your lips, not a sticker.
   - **Preserves specular highlights** (glossy highlight spots stay bright
     rather than being fully tinted).
   - **Detects your undertone** (warm / cool / neutral) from your natural
     lip color and gently harmonizes the product's hue toward it (~6°
     hue rotation), the way a makeup artist would color-correct rather than
     fight your undertone.
   - Reduces saturation slightly in shadow/crease areas so pigment doesn't
     look flat across the lip's 3D shape.
4. Switch between shades instantly, adjust intensity with a slider, and
   nothing is ever uploaded anywhere — the moment you refresh, your photo
   is gone.

## Getting started

```bash
npm install
npm run manifest   # scans /products, builds public/products/manifest.json
npm run dev        # starts local dev server
```

Open the printed local URL, add a couple of product photos to `/products`
first (see `/products/README.md`) if you want the shade rail populated.

## Adding products

Drop images into `/products` — see `/products/README.md` for naming and
photo guidelines. Then either:

- run `npm run manifest` locally and commit the result, or
- just commit the photos and push — the GitHub Action rebuilds the
  manifest automatically on every push to `main`.

## Deploying to GitHub Pages

This repo includes a GitHub Actions workflow
(`.github/workflows/deploy.yml`) that builds the site and deploys it to
GitHub Pages automatically on every push to `main`.

One-time setup after you push this repo to GitHub:

1. Go to **Settings → Pages** in your repository.
2. Under **Build and deployment → Source**, choose **GitHub Actions**.
3. Push to `main` (or re-run the workflow from the **Actions** tab).
4. Your site will be live at `https://<your-username>.github.io/<repo-name>/`.

The build automatically picks up your repo name for the correct base path
— no manual config needed, as long as you deploy via the included workflow.

### Deploying manually / elsewhere

```bash
npm run build     # outputs to /dist
```

If hosting somewhere other than GitHub Pages at a root domain, set
`REPO_NAME=""` as an env var before building (or edit the fallback in
`vite.config.js`) so asset paths resolve correctly.

## Tech stack

- **React + Vite** — UI and build tooling
- **MediaPipe Tasks Vision (Face Landmarker)** — in-browser face/lip
  landmark detection, loaded from Google's CDN, runs on-device via WASM/GPU
- **Canvas 2D API** — image manipulation and LAB color blending
- **sharp** (build-time only, in Node) — decoding product photos and
  extracting representative colors when generating the manifest
- No backend, no database, no analytics, no image uploads

## Project structure

```
products/                    # ← you add source photos here
public/products/             # generated: resized copies + manifest.json
scripts/build-manifest.js    # scans products/, extracts colors, writes manifest
src/
  lib/
    colorScience.js          # RGB<->LAB, undertone detection, lip recoloring
    lipDetection.js           # MediaPipe wrapper, lip mask generation
  components/                # UI
  App.jsx
.github/workflows/deploy.yml # CI: build + deploy to GitHub Pages
```

## Limitations

- Works best with clear, front-facing, well-lit photos where the mouth is
  closed or only slightly open.
- Face detection requires MediaPipe's model to load from Google's CDN on
  first use (cached afterward) — needs an internet connection the first
  time, even though no photo data is ever sent anywhere.
- Color extraction from product photos is automatic and works well for
  photos where the product color is clearly visible on the lips; heavily
  filtered or stylized photos may extract a less accurate color. You can
  always swap in a different, more representative photo and re-run
  `npm run manifest`.
ENDOFFILE_README_md

cat > 'index.html' << 'ENDOFFILE_index_html'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Try on lip color shades with real color-science blending, right in your browser. Nothing you upload ever leaves your device." />
    <title>Lip Shade Lab</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,500&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
ENDOFFILE_index_html

cat > 'package.json' << 'ENDOFFILE_package_json'
{
  "name": "lip-shade-lab",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "node scripts/build-manifest.js && vite build",
    "preview": "vite preview",
    "manifest": "node scripts/build-manifest.js"
  },
  "dependencies": {
    "@mediapipe/tasks-vision": "^0.10.14",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.1",
    "sharp": "^0.33.5",
    "vite": "^5.4.1"
  }
}
ENDOFFILE_package_json

mkdir -p 'products'
cat > 'products/README.md' << 'ENDOFFILE_products_README_md'
# Product photos go here

Drop photos of lip products **applied on lips** into this folder. Each
filename becomes the product's display name, so name your files the way
you'd want the product shown:

```
products/
  cherry-red-matte.jpg      -> "Cherry Red Matte"
  Rosewood_Velvet.png        -> "Rosewood Velvet"
  nude-glow.jpg              -> "Nude Glow"
```

Rules of thumb for good results:

- The photo should clearly show the product applied to lips (not just the
  tube/packaging) — the app samples color from the center of the image.
- Reasonably well-lit, minimal color-cast filters, product color plainly
  visible.
- `.jpg`, `.jpeg`, `.png`, or `.webp`.
- Use hyphens or underscores between words in filenames — they'll be
  converted to spaces and title-cased automatically.

After adding or changing photos, run:

```
npm run manifest
```

to regenerate the shade library, or just run `npm run build` /
push to `main` — the included GitHub Action rebuilds the manifest
automatically before deploying.
ENDOFFILE_products_README_md

mkdir -p 'public/products'
cat > 'public/products/.gitkeep' << 'ENDOFFILE_public_products__gitkeep'
ENDOFFILE_public_products__gitkeep

mkdir -p 'public/products'
cat > 'public/products/manifest.json' << 'ENDOFFILE_public_products_manifest_json'
{
  "products": [],
  "generatedAt": null
}
ENDOFFILE_public_products_manifest_json

mkdir -p 'scripts'
cat > 'scripts/build-manifest.js' << 'ENDOFFILE_scripts_build_manifest_js'
#!/usr/bin/env node
// ---------------------------------------------------------------------------
// Scans /products for image files, derives a product name from each
// filename, samples a representative color from the image using the same
// LAB-space logic as the in-browser color science module, and writes
// /public/products/manifest.json + copies (resized) images into
// /public/products/ for the app to consume at runtime.
//
// Usage: node scripts/build-manifest.js
// Runs automatically as part of `npm run build`.
// ---------------------------------------------------------------------------

import { readdirSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, extname, basename, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

// fileURLToPath + dirname works on any Node >=14 ESM build, unlike
// import.meta.dirname which needs Node 20.11+ — safer for CI runners that
// may be pinned to an older point release of a "Node 20" image.
const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SOURCE_DIR = join(ROOT, 'products')
const OUT_DIR = join(ROOT, 'public', 'products')
const MANIFEST_PATH = join(OUT_DIR, 'manifest.json')

const VALID_EXT = new Set(['.png', '.jpg', '.jpeg', '.webp'])

function titleCaseFromFilename(filename) {
  const stem = basename(filename, extname(filename))
  return stem
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .map((w) => (w.length ? w[0].toUpperCase() + w.slice(1) : w))
    .join(' ')
}

// --- LAB conversion (mirrors src/lib/colorScience.js so the manifest's
// stored color matches what the app would compute if it re-sampled) --------

function srgbToLinear(c) {
  c /= 255
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)
}

function rgbToLab([r, g, b]) {
  const lr = srgbToLinear(r)
  const lg = srgbToLinear(g)
  const lb = srgbToLinear(b)
  const x = 0.4124564 * lr + 0.3575761 * lg + 0.1804375 * lb
  const y = 0.2126729 * lr + 0.7151522 * lg + 0.072175 * lb
  const z = 0.0193339 * lr + 0.119192 * lg + 0.9503041 * lb
  const REF_X = 0.95047
  const REF_Y = 1.0
  const REF_Z = 1.08883
  const f = (t) => (t > 0.008856 ? Math.cbrt(t) : t / 0.128418 + 0.137931)
  const fx = f(x / REF_X)
  const fy = f(y / REF_Y)
  const fz = f(z / REF_Z)
  return [116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)]
}

function labToHex(lab) {
  const fy = (lab[0] + 16) / 116
  const fx = fy + lab[1] / 500
  const fz = fy - lab[2] / 200
  const finv = (t) => (t > 6 / 29 ? t * t * t : 3 * (6 / 29) ** 2 * (t - 4 / 29))
  const REF_X = 0.95047
  const REF_Y = 1.0
  const REF_Z = 1.08883
  const x = finv(fx) * REF_X
  const y = finv(fy) * REF_Y
  const z = finv(fz) * REF_Z
  const lin2s = (c) => (c <= 0.0031308 ? c * 12.92 : 1.055 * Math.pow(c, 1 / 2.4) - 0.055)
  let r = 3.2404542 * x - 1.5371385 * y - 0.4985314 * z
  let g = -0.969266 * x + 1.876011 * y + 0.041556 * z
  let b = 0.0556434 * x - 0.2040259 * y + 1.0572252 * z
  ;[r, g, b] = [r, g, b].map((c) => Math.max(0, Math.min(255, Math.round(lin2s(c) * 255))))
  return '#' + [r, g, b].map((c) => c.toString(16).padStart(2, '0')).join('')
}

/**
 * Sample the central band of the image (avoiding edges/background), filter
 * to plausible "product on lips" pixels (saturated, mid-lightness), and
 * take the LAB median — robust to specular highlights and stray background.
 */
function extractDominantLab({ data, info }) {
  const { width, height, channels } = info
  const samples = []
  const xStart = Math.floor(width * 0.25)
  const xEnd = Math.floor(width * 0.75)
  const yStart = Math.floor(height * 0.35)
  const yEnd = Math.floor(height * 0.75)

  for (let y = yStart; y < yEnd; y += 2) {
    for (let x = xStart; x < xEnd; x += 2) {
      const i = (y * width + x) * channels
      const r = data[i]
      const g = data[i + 1]
      const b = data[i + 2]
      const max = Math.max(r, g, b)
      const min = Math.min(r, g, b)
      const lightness = (max + min) / 2
      const sat = max === min ? 0 : (max - min) / (255 - Math.abs(2 * lightness - 255))
      if (lightness > 240 || lightness < 15) continue
      if (sat < 0.12) continue
      samples.push(rgbToLab([r, g, b]))
    }
  }
  if (samples.length === 0) {
    for (let y = yStart; y < yEnd; y += 3) {
      for (let x = xStart; x < xEnd; x += 3) {
        const i = (y * width + x) * channels
        samples.push(rgbToLab([data[i], data[i + 1], data[i + 2]]))
      }
    }
  }
  samples.sort((a, b) => a[0] - b[0])
  return samples[Math.floor(samples.length / 2)] || [50, 20, 10]
}

async function main() {
  if (!existsSync(SOURCE_DIR)) {
    mkdirSync(SOURCE_DIR, { recursive: true })
    console.log('Created empty /products directory. Add product photos there and re-run.')
  }
  mkdirSync(OUT_DIR, { recursive: true })

  const files = existsSync(SOURCE_DIR)
    ? readdirSync(SOURCE_DIR).filter((f) => VALID_EXT.has(extname(f).toLowerCase()))
    : []

  if (files.length === 0) {
    writeFileSync(
      MANIFEST_PATH,
      JSON.stringify({ products: [], generatedAt: new Date().toISOString() }, null, 2)
    )
    console.log('No product images found in /products. Wrote empty manifest.')
    return
  }

  const products = []

  for (const file of files) {
    const srcPath = join(SOURCE_DIR, file)
    const ext = extname(file).toLowerCase()
    // Normalize everything to web-friendly jpg on the way out, capped at a
    // sane max dimension so the repo/site stays light.
    const destName = basename(file, ext) + '.jpg'
    const destPath = join(OUT_DIR, destName)

    try {
      const image = sharp(srcPath).rotate() // auto-orient using EXIF
      const resized = image.resize({ width: 800, height: 800, fit: 'inside', withoutEnlargement: true })

      const { data, info } = await resized.clone().ensureAlpha().raw().toBuffer({ resolveWithObject: true })

      const lab = extractDominantLab({ data, info })
      const hex = labToHex(lab)

      await resized.clone().jpeg({ quality: 88 }).toFile(destPath)

      products.push({
        id: basename(file, ext).toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        name: titleCaseFromFilename(file),
        image: `products/${destName}`,
        lab,
        hex,
      })
      console.log(`✓ ${file} -> "${titleCaseFromFilename(file)}" (${hex})`)
    } catch (err) {
      console.warn(`⚠ Skipped ${file}: ${err.message}`)
    }
  }

  products.sort((a, b) => a.name.localeCompare(b.name))
  writeFileSync(
    MANIFEST_PATH,
    JSON.stringify({ products, generatedAt: new Date().toISOString() }, null, 2)
  )
  console.log(`\nWrote manifest with ${products.length} product(s) to ${MANIFEST_PATH}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
ENDOFFILE_scripts_build_manifest_js

mkdir -p 'src'
cat > 'src/App.jsx' << 'ENDOFFILE_src_App_jsx'
import { useEffect, useState } from 'react'
import Header from './components/Header.jsx'
import PhotoStage from './components/PhotoStage.jsx'
import ShadeRail from './components/ShadeRail.jsx'
import ReadoutStrip from './components/ReadoutStrip.jsx'
import IntensityControl from './components/IntensityControl.jsx'
import EmptyProductsNotice from './components/EmptyProductsNotice.jsx'
import './styles/app.css'

const MANIFEST_URL = `${import.meta.env.BASE_URL}products/manifest.json`

export default function App() {
  const [products, setProducts] = useState(null) // null = loading
  const [selectedId, setSelectedId] = useState(null)
  const [intensity, setIntensity] = useState(0.85)
  const [personPhoto, setPersonPhoto] = useState(null) // { element, width, height }
  const [lipData, setLipData] = useState(null) // { mask, naturalLab, undertone, boundingBox }
  const [detectionState, setDetectionState] = useState('idle') // idle | detecting | done | no-face | error

  useEffect(() => {
    fetch(MANIFEST_URL)
      .then((r) => r.json())
      .then((data) => {
        setProducts(data.products || [])
        if (data.products && data.products.length > 0) {
          setSelectedId(data.products[0].id)
        }
      })
      .catch(() => setProducts([]))
  }, [])

  const selectedProduct = products?.find((p) => p.id === selectedId) || null

  return (
    <div className="app-shell">
      <Header />

      <main className="workshop">
        <section className="stage-pane" aria-label="Photo and live preview">
          <PhotoStage
            personPhoto={personPhoto}
            setPersonPhoto={setPersonPhoto}
            lipData={lipData}
            setLipData={setLipData}
            detectionState={detectionState}
            setDetectionState={setDetectionState}
            selectedProduct={selectedProduct}
            intensity={intensity}
          />
          {lipData && (
            <ReadoutStrip lipData={lipData} selectedProduct={selectedProduct} />
          )}
          {lipData && (
            <IntensityControl intensity={intensity} setIntensity={setIntensity} />
          )}
        </section>

        <aside className="rail-pane" aria-label="Product shades">
          {products === null && <p className="rail-loading">Loading shade library…</p>}
          {products !== null && products.length === 0 && <EmptyProductsNotice />}
          {products && products.length > 0 && (
            <ShadeRail
              products={products}
              selectedId={selectedId}
              onSelect={setSelectedId}
            />
          )}
        </aside>
      </main>

      <footer className="app-footer">
        <p>
          Your photo is processed entirely in your browser and is never uploaded anywhere.
          Refresh the page and it&rsquo;s gone.
        </p>
      </footer>
    </div>
  )
}
ENDOFFILE_src_App_jsx

mkdir -p 'src/components'
cat > 'src/components/EmptyProductsNotice.jsx' << 'ENDOFFILE_src_components_EmptyProductsNotice_jsx'
export default function EmptyProductsNotice() {
  return (
    <div className="empty-products">
      <h2 className="rail-heading">Shades</h2>
      <p>No products yet.</p>
      <p className="empty-products-hint">
        Add photos to the <code>/products</code> folder in the repository (filename becomes
        the product name) and rebuild the site.
      </p>
    </div>
  )
}
ENDOFFILE_src_components_EmptyProductsNotice_jsx

mkdir -p 'src/components'
cat > 'src/components/Header.jsx' << 'ENDOFFILE_src_components_Header_jsx'
export default function Header() {
  return (
    <header className="app-header">
      <div className="app-header-mark" aria-hidden="true">
        <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
          <path
            d="M14 6c-4.5 0-8 2.8-8 7.2 0 2.9 2.3 5.1 5.2 6.3.9.4 1.6 1.1 1.9 2 .1.4.6.4.8 0 .3-.9 1-1.6 1.9-2 2.9-1.2 5.2-3.4 5.2-6.3C21 8.8 18.5 6 14 6z"
            fill="var(--berry)"
          />
        </svg>
      </div>
      <div>
        <h1>Lip Shade Lab</h1>
        <p className="app-header-sub">Try shades on, with real color science</p>
      </div>
    </header>
  )
}
ENDOFFILE_src_components_Header_jsx

mkdir -p 'src/components'
cat > 'src/components/IntensityControl.jsx' << 'ENDOFFILE_src_components_IntensityControl_jsx'
export default function IntensityControl({ intensity, setIntensity }) {
  return (
    <div className="intensity-control">
      <label htmlFor="intensity-slider" className="intensity-label">
        Intensity
      </label>
      <input
        id="intensity-slider"
        type="range"
        min="0.2"
        max="1"
        step="0.01"
        value={intensity}
        onChange={(e) => setIntensity(parseFloat(e.target.value))}
        className="intensity-slider"
      />
      <span className="intensity-value">{Math.round(intensity * 100)}%</span>
    </div>
  )
}
ENDOFFILE_src_components_IntensityControl_jsx

mkdir -p 'src/components'
cat > 'src/components/PhotoStage.jsx' << 'ENDOFFILE_src_components_PhotoStage_jsx'
import { useCallback, useEffect, useRef, useState } from 'react'
import { detectFaceLandmarks, buildLipMask, getLipBoundingBox } from '../lib/lipDetection.js'
import { recolorLips, rgbToLab, classifyUndertone } from '../lib/colorScience.js'

const MAX_DIMENSION = 1400 // cap decode size for performance

export default function PhotoStage({
  personPhoto,
  setPersonPhoto,
  lipData,
  setLipData,
  detectionState,
  setDetectionState,
  selectedProduct,
  intensity,
}) {
  const canvasRef = useRef(null)
  const fileInputRef = useRef(null)
  const [dragActive, setDragActive] = useState(false)

  const loadImageFile = useCallback(
    async (file) => {
      if (!file || !file.type.startsWith('image/')) return
      setDetectionState('detecting')
      setLipData(null)

      const objectUrl = URL.createObjectURL(file)
      const img = new Image()
      img.onload = async () => {
        // Downscale for performance while keeping enough resolution for the mask
        let { width, height } = img
        if (width > MAX_DIMENSION || height > MAX_DIMENSION) {
          const scale = MAX_DIMENSION / Math.max(width, height)
          width = Math.round(width * scale)
          height = Math.round(height * scale)
        }

        const canvas = document.createElement('canvas')
        canvas.width = width
        canvas.height = height
        const ctx = canvas.getContext('2d')
        ctx.drawImage(img, 0, 0, width, height)

        URL.revokeObjectURL(objectUrl)
        setPersonPhoto({ canvas, width, height })

        try {
          const landmarks = await detectFaceLandmarks(canvas)
          if (!landmarks) {
            setDetectionState('no-face')
            return
          }
          const mask = buildLipMask(landmarks, width, height, Math.max(3, width * 0.003))
          const boundingBox = getLipBoundingBox(landmarks, width, height)

          const imageData = ctx.getImageData(0, 0, width, height)
          let sumR = 0,
            sumG = 0,
            sumB = 0,
            n = 0
          for (let p = 0; p < width * height; p++) {
            if (mask[p] > 0.6) {
              const i = p * 4
              sumR += imageData.data[i]
              sumG += imageData.data[i + 1]
              sumB += imageData.data[i + 2]
              n++
            }
          }
          const naturalLab =
            n > 0 ? rgbToLab([sumR / n, sumG / n, sumB / n]) : [55, 25, 12]
          const undertone = classifyUndertone(naturalLab)

          setLipData({ mask, naturalLab, undertone, boundingBox })
          setDetectionState('done')
        } catch (err) {
          console.error('Face detection failed:', err)
          setDetectionState('error')
        }
      }
      img.onerror = () => {
        URL.revokeObjectURL(objectUrl)
        setDetectionState('error')
      }
      img.src = objectUrl
    },
    [setPersonPhoto, setLipData, setDetectionState]
  )

  // Re-render the canvas whenever product, intensity, or photo changes
  useEffect(() => {
    if (!personPhoto || !canvasRef.current) return
    const canvas = canvasRef.current
    canvas.width = personPhoto.width
    canvas.height = personPhoto.height
    const ctx = canvas.getContext('2d')

    if (!lipData || !selectedProduct) {
      ctx.drawImage(personPhoto.canvas, 0, 0)
      return
    }

    const sourceCtx = personPhoto.canvas.getContext('2d')
    const sourceImageData = sourceCtx.getImageData(0, 0, personPhoto.width, personPhoto.height)
    const recolored = recolorLips(sourceImageData, lipData.mask, selectedProduct.lab, {
      intensity,
      glossPreserve: 0.35,
    })
    ctx.putImageData(recolored, 0, 0)
  }, [personPhoto, lipData, selectedProduct, intensity])

  const handleFileChange = (e) => {
    const file = e.target.files?.[0]
    if (file) loadImageFile(file)
  }

  const handleDrop = (e) => {
    e.preventDefault()
    setDragActive(false)
    const file = e.dataTransfer.files?.[0]
    if (file) loadImageFile(file)
  }

  const handleReset = () => {
    setPersonPhoto(null)
    setLipData(null)
    setDetectionState('idle')
    if (fileInputRef.current) fileInputRef.current.value = ''
  }

  if (!personPhoto) {
    return (
      <div
        className={`upload-dropzone ${dragActive ? 'drag-active' : ''}`}
        onDragOver={(e) => {
          e.preventDefault()
          setDragActive(true)
        }}
        onDragLeave={() => setDragActive(false)}
        onDrop={handleDrop}
        onClick={() => fileInputRef.current?.click()}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') fileInputRef.current?.click()
        }}
      >
        <svg width="40" height="40" viewBox="0 0 40 40" fill="none" aria-hidden="true">
          <rect x="4" y="8" width="32" height="26" rx="1" stroke="var(--ink-soft)" strokeWidth="1.5" />
          <circle cx="14" cy="17" r="3" stroke="var(--ink-soft)" strokeWidth="1.5" />
          <path d="M4 28l9-8 6 5 8-9 9 10" stroke="var(--ink-soft)" strokeWidth="1.5" strokeLinejoin="round" />
        </svg>
        <p className="upload-title">Add a photo to try on shades</p>
        <p className="upload-hint">Drop an image here, or click to choose one — front-facing, lips visible</p>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          onChange={handleFileChange}
          className="visually-hidden"
        />
      </div>
    )
  }

  return (
    <div className="stage-canvas-wrap">
      <canvas ref={canvasRef} className="stage-canvas" />

      {detectionState === 'detecting' && (
        <div className="stage-overlay">
          <p>Finding your lips…</p>
        </div>
      )}

      {detectionState === 'no-face' && (
        <div className="stage-overlay stage-overlay-warn">
          <p>Couldn&rsquo;t find a face in that photo.</p>
          <p className="stage-overlay-hint">Try a clearer, front-facing photo with lips visible.</p>
          <button className="btn-ghost" onClick={handleReset}>
            Try another photo
          </button>
        </div>
      )}

      {detectionState === 'error' && (
        <div className="stage-overlay stage-overlay-warn">
          <p>Something went wrong reading that image.</p>
          <button className="btn-ghost" onClick={handleReset}>
            Try another photo
          </button>
        </div>
      )}

      {detectionState === 'done' && (
        <button className="btn-ghost stage-reset" onClick={handleReset}>
          Use a different photo
        </button>
      )}
    </div>
  )
}
ENDOFFILE_src_components_PhotoStage_jsx

mkdir -p 'src/components'
cat > 'src/components/ReadoutStrip.jsx' << 'ENDOFFILE_src_components_ReadoutStrip_jsx'
const UNDERTONE_LABEL = {
  warm: 'Warm',
  cool: 'Cool',
  neutral: 'Neutral',
}

export default function ReadoutStrip({ lipData, selectedProduct }) {
  const { naturalLab, undertone } = lipData

  return (
    <div className="readout-strip" aria-label="Color analysis">
      <div className="readout-item">
        <span className="readout-label">Your lip undertone</span>
        <span className="readout-value">{UNDERTONE_LABEL[undertone] || 'Neutral'}</span>
      </div>
      <div className="readout-divider" aria-hidden="true" />
      <div className="readout-item">
        <span className="readout-label">Natural tone</span>
        <span className="readout-value readout-value-swatch">
          <span
            className="readout-dot"
            style={{ backgroundColor: labToDisplayHex(naturalLab) }}
            aria-hidden="true"
          />
          L {naturalLab[0].toFixed(0)}
        </span>
      </div>
      {selectedProduct && (
        <>
          <div className="readout-divider" aria-hidden="true" />
          <div className="readout-item">
            <span className="readout-label">Applied shade</span>
            <span className="readout-value readout-value-swatch">
              <span
                className="readout-dot"
                style={{ backgroundColor: selectedProduct.hex }}
                aria-hidden="true"
              />
              {selectedProduct.name}
            </span>
          </div>
        </>
      )}
    </div>
  )
}

// Lightweight LAB->hex just for the readout dot (avoids importing the full
// color science module's canvas-dependent helpers here)
function labToDisplayHex([L, a, b]) {
  const fy = (L + 16) / 116
  const fx = fy + a / 500
  const fz = fy - b / 200
  const finv = (t) => (t > 6 / 29 ? t ** 3 : 3 * (6 / 29) ** 2 * (t - 4 / 29))
  const x = finv(fx) * 0.95047
  const y = finv(fy) * 1.0
  const z = finv(fz) * 1.08883
  const lin2s = (c) => (c <= 0.0031308 ? c * 12.92 : 1.055 * Math.pow(Math.max(c, 0), 1 / 2.4) - 0.055)
  let r = 3.2404542 * x - 1.5371385 * y - 0.4985314 * z
  let g = -0.969266 * x + 1.876011 * y + 0.041556 * z
  let bch = 0.0556434 * x - 0.2040259 * y + 1.0572252 * z
  ;[r, g, bch] = [r, g, bch].map((c) => Math.max(0, Math.min(255, Math.round(lin2s(c) * 255))))
  return `#${[r, g, bch].map((c) => c.toString(16).padStart(2, '0')).join('')}`
}
ENDOFFILE_src_components_ReadoutStrip_jsx

mkdir -p 'src/components'
cat > 'src/components/ShadeRail.jsx' << 'ENDOFFILE_src_components_ShadeRail_jsx'
export default function ShadeRail({ products, selectedId, onSelect }) {
  return (
    <div className="shade-rail">
      <h2 className="rail-heading">Shades</h2>
      <p className="rail-count">
        {products.length} product{products.length === 1 ? '' : 's'}
      </p>
      <ul className="shade-list" role="listbox" aria-label="Select a shade">
        {products.map((product) => {
          const isSelected = product.id === selectedId
          return (
            <li key={product.id}>
              <button
                className={`shade-item ${isSelected ? 'shade-item-selected' : ''}`}
                role="option"
                aria-selected={isSelected}
                onClick={() => onSelect(product.id)}
              >
                <span
                  className="shade-swatch"
                  style={{ backgroundColor: product.hex }}
                  aria-hidden="true"
                />
                <span className="shade-info">
                  <span className="shade-name">{product.name}</span>
                  <span className="shade-hex">{product.hex}</span>
                </span>
              </button>
            </li>
          )
        })}
      </ul>
    </div>
  )
}
ENDOFFILE_src_components_ShadeRail_jsx

mkdir -p 'src/lib'
cat > 'src/lib/colorScience.js' << 'ENDOFFILE_src_lib_colorScience_js'
// ---------------------------------------------------------------------------
// Color science core.
//
// Everything here works in CIE LAB space rather than raw RGB. RGB mixes light
// the way a screen emits it, not the way a pigment sits on skin — blending
// two RGB values head-on gives you a muddy average, not a plausible lipstick.
// LAB separates *lightness* (L) from *hue+chroma* (a/b), which is what lets
// us keep a person's natural lip shading (highlights, the cupid's bow shadow,
// texture) while swapping in a product's actual color.
// ---------------------------------------------------------------------------

// --- sRGB <-> Linear RGB -----------------------------------------------------

function srgbToLinear(c) {
  c /= 255
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)
}

function linearToSrgb(c) {
  const v = c <= 0.0031308 ? c * 12.92 : 1.055 * Math.pow(c, 1 / 2.4) - 0.055
  return Math.max(0, Math.min(255, Math.round(v * 255)))
}

// --- Linear RGB <-> XYZ (D65) -----------------------------------------------

const RGB_TO_XYZ = [
  [0.4124564, 0.3575761, 0.1804375],
  [0.2126729, 0.7151522, 0.072175],
  [0.0193339, 0.119192, 0.9503041],
]
const XYZ_TO_RGB = [
  [3.2404542, -1.5371385, -0.4985314],
  [-0.969266, 1.8760108, 0.041556],
  [0.0556434, -0.2040259, 1.0572252],
]

// D65 reference white
const REF_X = 0.95047
const REF_Y = 1.0
const REF_Z = 1.08883

function rgbToXyz([r, g, b]) {
  const lr = srgbToLinear(r)
  const lg = srgbToLinear(g)
  const lb = srgbToLinear(b)
  return [
    RGB_TO_XYZ[0][0] * lr + RGB_TO_XYZ[0][1] * lg + RGB_TO_XYZ[0][2] * lb,
    RGB_TO_XYZ[1][0] * lr + RGB_TO_XYZ[1][1] * lg + RGB_TO_XYZ[1][2] * lb,
    RGB_TO_XYZ[2][0] * lr + RGB_TO_XYZ[2][1] * lg + RGB_TO_XYZ[2][2] * lb,
  ]
}

function xyzToRgb([x, y, z]) {
  const r = XYZ_TO_RGB[0][0] * x + XYZ_TO_RGB[0][1] * y + XYZ_TO_RGB[0][2] * z
  const g = XYZ_TO_RGB[1][0] * x + XYZ_TO_RGB[1][1] * y + XYZ_TO_RGB[1][2] * z
  const b = XYZ_TO_RGB[2][0] * x + XYZ_TO_RGB[2][1] * y + XYZ_TO_RGB[2][2] * z
  return [linearToSrgb(r), linearToSrgb(g), linearToSrgb(b)]
}

// --- XYZ <-> LAB -------------------------------------------------------------

function fLab(t) {
  const d = 6 / 29
  return t > d * d * d ? Math.cbrt(t) : t / (3 * d * d) + 4 / 29
}

function fLabInv(t) {
  const d = 6 / 29
  return t > d ? t * t * t : 3 * d * d * (t - 4 / 29)
}

export function rgbToLab([r, g, b]) {
  const [x, y, z] = rgbToXyz([r, g, b])
  const fx = fLab(x / REF_X)
  const fy = fLab(y / REF_Y)
  const fz = fLab(z / REF_Z)
  return [116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)]
}

export function labToRgb([L, a, b]) {
  const fy = (L + 16) / 116
  const fx = fy + a / 500
  const fz = fy - b / 200
  const x = fLabInv(fx) * REF_X
  const y = fLabInv(fy) * REF_Y
  const z = fLabInv(fz) * REF_Z
  return xyzToRgb([x, y, z])
}

// --- Undertone classification ------------------------------------------------
//
// Undertone is estimated from the hue angle of the a/b vector: redder+more
// yellow (a>0, b leaning positive, hue angle roughly 15-55deg) reads warm;
// redder+more blue/pink (b near zero or negative) reads cool. This is a
// simplification of real skin-tone science but works well for lip pixels,
// which sit in a narrow hue band to begin with.

export function classifyUndertone(labColor) {
  const [, a, b] = labColor
  const hueAngle = (Math.atan2(b, a) * 180) / Math.PI
  if (hueAngle > 35) return 'warm'
  if (hueAngle < 15) return 'cool'
  return 'neutral'
}

// --- Product color extraction ------------------------------------------------

/**
 * Given raw RGBA pixel data (Uint8ClampedArray) of a *cropped* product photo
 * that shows lips wearing the product, extract a representative LAB color.
 *
 * Strategy: sample pixels in a central band (avoiding edges/background),
 * filter to plausible "lip pixel" hues (reddish/pink/nude range), then take
 * the median in LAB space (median is more robust to specular highlights and
 * stray background pixels than a mean).
 */
export function extractDominantLabColor(imageData, opts = {}) {
  const { width, height, data } = imageData
  const samples = []

  const xStart = Math.floor(width * (opts.xStart ?? 0.25))
  const xEnd = Math.floor(width * (opts.xEnd ?? 0.75))
  const yStart = Math.floor(height * (opts.yStart ?? 0.35))
  const yEnd = Math.floor(height * (opts.yEnd ?? 0.75))

  for (let y = yStart; y < yEnd; y += 2) {
    for (let x = xStart; x < xEnd; x += 2) {
      const i = (y * width + x) * 4
      const r = data[i]
      const g = data[i + 1]
      const b = data[i + 2]
      const alpha = data[i + 3]
      if (alpha < 200) continue

      // Reject near-white/near-black/near-gray pixels (likely background,
      // studio lighting blowouts, or shadow, not the product itself)
      const max = Math.max(r, g, b)
      const min = Math.min(r, g, b)
      const lightness = (max + min) / 2
      const sat = max === min ? 0 : (max - min) / (255 - Math.abs(2 * lightness - 255))
      if (lightness > 240 || lightness < 15) continue
      if (sat < 0.12) continue

      samples.push(rgbToLab([r, g, b]))
    }
  }

  if (samples.length === 0) {
    // Fallback: just average the whole center crop without filtering
    for (let y = yStart; y < yEnd; y += 3) {
      for (let x = xStart; x < xEnd; x += 3) {
        const i = (y * width + x) * 4
        samples.push(rgbToLab([data[i], data[i + 1], data[i + 2]]))
      }
    }
  }

  samples.sort((s1, s2) => s1[0] - s2[0])
  const median = samples[Math.floor(samples.length / 2)] || [50, 20, 10]
  return median
}

// --- Lip recoloring ----------------------------------------------------------

/**
 * Recolor a person's lips using their natural lightness/shading, the
 * product's hue+chroma, and undertone-aware harmonization.
 *
 * @param {ImageData} personImageData - full photo pixel data (will be copied, not mutated)
 * @param {Float32Array} lipMask - same width*height, values 0..1 (soft mask, 1 = fully lip)
 * @param {[number,number,number]} productLab - product's representative LAB color
 * @param {object} opts
 * @param {number} opts.intensity - 0..1, how strongly to apply product color (product "opacity")
 * @param {number} opts.glossPreserve - 0..1, how much to preserve bright specular highlights as white/light rather than tinting them fully
 * @returns {ImageData} new ImageData with lips recolored
 */
export function recolorLips(personImageData, lipMask, productLab, opts = {}) {
  const { width, height, data } = personImageData
  const intensity = opts.intensity ?? 0.85
  const glossPreserve = opts.glossPreserve ?? 0.35

  const out = new ImageData(new Uint8ClampedArray(data), width, height)
  const outData = out.data

  // First pass: find the median natural lip LAB (for undertone + reference midtone)
  let sumL = 0,
    count = 0
  const labCache = new Array(width * height)
  for (let p = 0; p < width * height; p++) {
    const m = lipMask[p]
    if (m < 0.15) continue
    const i = p * 4
    const lab = rgbToLab([data[i], data[i + 1], data[i + 2]])
    labCache[p] = lab
    sumL += lab[0]
    count++
  }
  const naturalLabAvg = count > 0 ? sumL / count : 50
  const midtoneL = naturalLabAvg

  const [prodL, prodA, prodB] = productLab
  const personUndertone = (() => {
    // Sample a rough undertone estimate from natural lip pixels
    let aSum = 0,
      bSum = 0,
      n = 0
    for (let p = 0; p < width * height; p++) {
      if (lipMask[p] > 0.5 && labCache[p]) {
        aSum += labCache[p][1]
        bSum += labCache[p][2]
        n++
      }
    }
    if (n === 0) return 'neutral'
    return classifyUndertone([50, aSum / n, bSum / n])
  })()

  // Undertone harmonization: nudge product hue slightly toward the person's
  // undertone rather than fighting it. This is subtle by design (max ~8deg
  // hue rotation) — real MUA color-correction, not a filter.
  const hueShiftDeg = personUndertone === 'warm' ? 6 : personUndertone === 'cool' ? -6 : 0
  const theta = (hueShiftDeg * Math.PI) / 180
  const adjA = prodA * Math.cos(theta) - prodB * Math.sin(theta)
  const adjB = prodA * Math.sin(theta) + prodB * Math.cos(theta)

  for (let p = 0; p < width * height; p++) {
    const m = lipMask[p]
    if (m <= 0.01) continue
    const i = p * 4
    const naturalLab = labCache[p] || rgbToLab([data[i], data[i + 1], data[i + 2]])
    const [nL, nA, nB] = naturalLab

    // Preserve specular highlights: pixels much brighter than the lip
    // midtone are glossy highlights — pull them back toward natural color
    // rather than fully tinting, so the lips keep dimensional shine.
    const highlightFactor = Math.max(0, Math.min(1, (nL - midtoneL) / 35))
    const highlightPreserve = highlightFactor * glossPreserve

    // Target lightness: keep the person's own shading almost entirely (this
    // is what makes the result look like the product sitting on *their*
    // lips, not a cutout). Nudge very slightly toward the product's own
    // reference lightness so very dark or very light products still read.
    const targetL = nL * 0.88 + prodL * 0.12

    // Chroma modulation: pixels in shadow/crease areas (low L relative to
    // midtone) get slightly reduced saturation, mimicking how pigment
    // gathers less light in recesses — avoids a flat "sticker" look.
    const shadowFactor = Math.max(0.55, Math.min(1, 1 - (midtoneL - nL) / 120))

    const blendStrength = intensity * (1 - highlightPreserve) * (1 - m * 0) * m
    const finalL = nL * (1 - blendStrength) + targetL * blendStrength
    const finalA = nA * (1 - blendStrength) + adjA * shadowFactor * blendStrength
    const finalB = nB * (1 - blendStrength) + adjB * shadowFactor * blendStrength

    const [r, g, b] = labToRgb([finalL, finalA, finalB])
    outData[i] = r
    outData[i + 1] = g
    outData[i + 2] = b
    outData[i + 3] = data[i + 3]
  }

  return out
}
ENDOFFILE_src_lib_colorScience_js

mkdir -p 'src/lib'
cat > 'src/lib/lipDetection.js' << 'ENDOFFILE_src_lib_lipDetection_js'
import { FaceLandmarker, FilesetResolver } from '@mediapipe/tasks-vision'

// MediaPipe FaceMesh landmark indices that trace the lip boundary.
// Outer lip contour (the visible outer edge of the mouth):
const OUTER_LIP_INDICES = [
  61, 146, 91, 181, 84, 17, 314, 405, 321, 375, 291, 308, 324, 318, 402, 317,
  14, 87, 178, 88, 95, 61,
]

// Inner lip contour (the inner edge, i.e. where the mouth opening begins) —
// used to exclude teeth/mouth-interior from the mask so we don't tint teeth.
const INNER_LIP_INDICES = [
  78, 95, 88, 178, 87, 14, 317, 402, 318, 324, 308, 415, 310, 311, 312, 13,
  82, 81, 80, 191, 78,
]

let landmarkerPromise = null

/**
 * Lazily create and cache the FaceLandmarker instance. Loads the WASM
 * runtime + model from a CDN on first use (cached by the browser after).
 */
function getLandmarker() {
  if (!landmarkerPromise) {
    landmarkerPromise = (async () => {
      const vision = await FilesetResolver.forVisionTasks(
        'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm'
      )
      return FaceLandmarker.createFromOptions(vision, {
        baseOptions: {
          modelAssetPath:
            'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',
          delegate: 'GPU',
        },
        outputFaceBlendshapes: false,
        outputFacialTransformationMatrixes: false,
        runningMode: 'IMAGE',
        numFaces: 1,
      })
    })()
  }
  return landmarkerPromise
}

/**
 * Detect face landmarks in an HTMLImageElement (or canvas/video).
 * Returns null if no face was found.
 */
export async function detectFaceLandmarks(imageElement) {
  const landmarker = await getLandmarker()
  const result = landmarker.detect(imageElement)
  if (!result.faceLandmarks || result.faceLandmarks.length === 0) {
    return null
  }
  return result.faceLandmarks[0] // array of {x, y, z} normalized 0..1
}

/**
 * Build a soft-edged lip mask (Float32Array, values 0..1, length width*height)
 * from face landmarks. The mask is 1.0 well inside the lip contour, fades to
 * 0 over a feather region at the boundary, and is 0 outside — and it also
 * excludes the mouth interior (teeth/tongue/dark cavity) via the inner
 * contour, so open-mouth photos don't get teeth tinted.
 */
export function buildLipMask(landmarks, width, height, featherPx = 4) {
  const outerPts = OUTER_LIP_INDICES.map((idx) => ({
    x: landmarks[idx].x * width,
    y: landmarks[idx].y * height,
  }))
  const innerPts = INNER_LIP_INDICES.map((idx) => ({
    x: landmarks[idx].x * width,
    y: landmarks[idx].y * height,
  }))

  // Rasterize outer polygon minus inner polygon onto an offscreen canvas,
  // then feather with a small blur pass done manually on the alpha channel.
  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height
  const ctx = canvas.getContext('2d')

  ctx.clearRect(0, 0, width, height)
  ctx.fillStyle = '#fff'
  ctx.beginPath()
  outerPts.forEach((pt, i) => (i === 0 ? ctx.moveTo(pt.x, pt.y) : ctx.lineTo(pt.x, pt.y)))
  ctx.closePath()
  // Cut out the mouth interior using even-odd fill rule
  ctx.moveTo(innerPts[0].x, innerPts[0].y)
  for (let i = innerPts.length - 1; i >= 0; i--) {
    ctx.lineTo(innerPts[i].x, innerPts[i].y)
  }
  ctx.closePath()
  ctx.fill('evenodd')

  // Feather the mask edges with a gaussian-ish blur for a natural transition
  ctx.filter = `blur(${featherPx}px)`
  const blurred = document.createElement('canvas')
  blurred.width = width
  blurred.height = height
  const bctx = blurred.getContext('2d')
  bctx.filter = `blur(${featherPx}px)`
  bctx.drawImage(canvas, 0, 0)

  const imgData = bctx.getImageData(0, 0, width, height)
  const mask = new Float32Array(width * height)
  for (let p = 0; p < width * height; p++) {
    mask[p] = imgData.data[p * 4] / 255 // red channel carries the white-fill alpha after blur
  }
  return mask
}

/** Convenience: bounding box of the outer lip landmarks, in pixel coords. */
export function getLipBoundingBox(landmarks, width, height) {
  const pts = OUTER_LIP_INDICES.map((idx) => ({
    x: landmarks[idx].x * width,
    y: landmarks[idx].y * height,
  }))
  const xs = pts.map((p) => p.x)
  const ys = pts.map((p) => p.y)
  return {
    minX: Math.min(...xs),
    maxX: Math.max(...xs),
    minY: Math.min(...ys),
    maxY: Math.max(...ys),
  }
}
ENDOFFILE_src_lib_lipDetection_js

mkdir -p 'src'
cat > 'src/main.jsx' << 'ENDOFFILE_src_main_jsx'
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './styles/global.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
ENDOFFILE_src_main_jsx

mkdir -p 'src/styles'
cat > 'src/styles/app.css' << 'ENDOFFILE_src_styles_app_css'
/* ---------------------------------------------------------------- Shell */

.app-shell {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.app-header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 28px 40px 20px;
  border-bottom: 1px solid var(--line);
}

.app-header-mark {
  flex-shrink: 0;
  display: flex;
}

.app-header h1 {
  font-size: 22px;
  letter-spacing: -0.01em;
}

.app-header-sub {
  font-size: 13px;
  color: var(--ink-soft);
  margin-top: 2px;
}

.app-footer {
  padding: 18px 40px 28px;
  border-top: 1px solid var(--line);
  margin-top: auto;
}

.app-footer p {
  font-size: 12.5px;
  color: var(--ink-soft);
  max-width: 60ch;
}

/* ------------------------------------------------------------- Workshop */

.workshop {
  flex: 1;
  display: grid;
  grid-template-columns: 1fr 320px;
  gap: 40px;
  padding: 32px 40px;
  align-items: start;
}

@media (max-width: 860px) {
  .workshop {
    grid-template-columns: 1fr;
    padding: 20px;
    gap: 28px;
  }
}

.stage-pane {
  display: flex;
  flex-direction: column;
  gap: 16px;
  min-width: 0;
}

/* --------------------------------------------------------- Upload zone */

.upload-dropzone {
  border: 1.5px dashed var(--line-strong);
  border-radius: 4px;
  min-height: 420px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
  text-align: center;
  padding: 40px;
  cursor: pointer;
  transition: border-color 0.15s ease, background-color 0.15s ease;
  background: var(--paper-dim);
}

.upload-dropzone:hover,
.upload-dropzone.drag-active {
  border-color: var(--berry);
  background: var(--clay-soft);
}

.upload-title {
  font-family: var(--font-display);
  font-size: 19px;
  margin-top: 8px;
}

.upload-hint {
  font-size: 13px;
  color: var(--ink-soft);
  max-width: 34ch;
}

/* ------------------------------------------------------------- Canvas */

.stage-canvas-wrap {
  position: relative;
  border-radius: 4px;
  overflow: hidden;
  background: var(--paper-dim);
  border: 1px solid var(--line);
  line-height: 0;
}

.stage-canvas {
  width: 100%;
  height: auto;
  display: block;
}

.stage-overlay {
  position: absolute;
  inset: 0;
  background: rgba(28, 24, 21, 0.72);
  color: var(--paper);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  text-align: center;
  padding: 24px;
}

.stage-overlay p {
  font-size: 15px;
}

.stage-overlay-hint {
  font-size: 13px;
  opacity: 0.8;
  max-width: 32ch;
}

.stage-overlay-warn .btn-ghost {
  margin-top: 8px;
  border-color: var(--paper);
  color: var(--paper);
}

.stage-reset {
  position: absolute;
  bottom: 14px;
  right: 14px;
}

.btn-ghost {
  background: rgba(247, 243, 239, 0.92);
  border: 1px solid var(--line-strong);
  border-radius: 3px;
  padding: 7px 14px;
  font-size: 13px;
  color: var(--ink);
  font-weight: 500;
}

.btn-ghost:hover {
  border-color: var(--berry);
  color: var(--berry);
}

/* ------------------------------------------------------------ Readout */

.readout-strip {
  display: flex;
  align-items: center;
  gap: 18px;
  padding: 14px 18px;
  background: var(--paper-dim);
  border: 1px solid var(--line);
  border-radius: 4px;
  flex-wrap: wrap;
}

.readout-item {
  display: flex;
  flex-direction: column;
  gap: 3px;
}

.readout-label {
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--ink-soft);
}

.readout-value {
  font-size: 14px;
  font-weight: 500;
}

.readout-value-swatch {
  display: flex;
  align-items: center;
  gap: 6px;
}

.readout-dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  border: 1px solid rgba(0, 0, 0, 0.15);
  flex-shrink: 0;
}

.readout-divider {
  width: 1px;
  height: 28px;
  background: var(--line-strong);
}

/* --------------------------------------------------------- Intensity */

.intensity-control {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 4px 4px;
}

.intensity-label {
  font-size: 12.5px;
  color: var(--ink-soft);
  min-width: 54px;
}

.intensity-slider {
  flex: 1;
  accent-color: var(--berry);
}

.intensity-value {
  font-size: 12.5px;
  color: var(--ink-soft);
  min-width: 38px;
  text-align: right;
  font-variant-numeric: tabular-nums;
}

/* -------------------------------------------------------------- Rail */

.rail-pane {
  min-width: 0;
}

.rail-heading {
  font-size: 18px;
  margin-bottom: 2px;
}

.rail-count {
  font-size: 12.5px;
  color: var(--ink-soft);
  margin-bottom: 16px;
}

.rail-loading {
  font-size: 13px;
  color: var(--ink-soft);
}

.shade-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
  max-height: 640px;
  overflow-y: auto;
}

.shade-item {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 9px 10px;
  background: transparent;
  border: 1px solid transparent;
  border-radius: 4px;
  text-align: left;
}

.shade-item:hover {
  background: var(--paper-dim);
}

.shade-item-selected {
  background: var(--clay-soft);
  border-color: var(--clay);
}

.shade-swatch {
  width: 30px;
  height: 30px;
  border-radius: 50%;
  border: 1px solid rgba(0, 0, 0, 0.15);
  flex-shrink: 0;
  box-shadow: inset 0 -3px 5px rgba(0, 0, 0, 0.18), inset 0 2px 3px rgba(255, 255, 255, 0.25);
}

.shade-info {
  display: flex;
  flex-direction: column;
  gap: 1px;
  min-width: 0;
}

.shade-name {
  font-size: 13.5px;
  font-weight: 500;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.shade-hex {
  font-size: 11.5px;
  color: var(--ink-soft);
  font-variant-numeric: tabular-nums;
  text-transform: uppercase;
}

/* --------------------------------------------------------- Empty state */

.empty-products {
  padding: 4px 0;
}

.empty-products-hint {
  font-size: 13px;
  color: var(--ink-soft);
  margin-top: 8px;
  max-width: 36ch;
}

.empty-products code {
  background: var(--paper-dim);
  padding: 1px 5px;
  border-radius: 3px;
  font-size: 12.5px;
}
ENDOFFILE_src_styles_app_css

mkdir -p 'src/styles'
cat > 'src/styles/global.css' << 'ENDOFFILE_src_styles_global_css'
:root {
  --paper: #f7f3ef;
  --paper-dim: #efe8e1;
  --ink: #1c1815;
  --ink-soft: #574f48;
  --line: #ddd4cc;
  --line-strong: #c3b7ab;
  --berry: #7a1f3d;
  --berry-dark: #591530;
  --clay: #c97b6e;
  --clay-soft: #f0ddd6;
  --success: #4c7a5e;
  --warn: #a8632c;

  --font-display: 'Fraunces', Georgia, serif;
  --font-ui: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;

  color-scheme: light;
}

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  padding: 0;
}

body {
  background: var(--paper);
  color: var(--ink);
  font-family: var(--font-ui);
  font-size: 15px;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}

#root {
  min-height: 100vh;
}

h1,
h2,
h3 {
  font-family: var(--font-display);
  font-weight: 500;
  margin: 0;
  color: var(--ink);
}

p {
  margin: 0;
}

button {
  font-family: var(--font-ui);
  cursor: pointer;
}

button:focus-visible,
[tabindex]:focus-visible,
input:focus-visible {
  outline: 2px solid var(--berry);
  outline-offset: 2px;
}

img {
  max-width: 100%;
  display: block;
}

::selection {
  background: var(--clay-soft);
  color: var(--berry-dark);
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
  white-space: nowrap;
}

@media (prefers-reduced-motion: reduce) {
  * {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
ENDOFFILE_src_styles_global_css

cat > 'vite.config.js' << 'ENDOFFILE_vite_config_js'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// GitHub Pages serves project sites from /<repo-name>/, so the base path
// must match the repository name. Set REPO_NAME as an env var at build time
// (the included GitHub Action does this automatically), or edit the
// fallback string below to match your repo.
const repoName = process.env.REPO_NAME || 'lip-shade-lab'

export default defineConfig({
  plugins: [react()],
  base: process.env.NODE_ENV === 'production' ? `/${repoName}/` : '/',
})
ENDOFFILE_vite_config_js

echo "Done. All files created."
echo "Next: run npm install"
